##########################################################################
# File: dkcoder\.github\workflows\ninja-build-static.yml                 #
#                                                                        #
# Copyright 2024 Diskuv, Inc.                                            #
#                                                                        #
# Licensed under the Open Software License version 3.0                   #
# (the "License"); you may not use this file except in compliance        #
# with the License. You may obtain a copy of the License at              #
#                                                                        #
#     https://opensource.org/license/osl-3-0-php/                        #
#                                                                        #
##########################################################################

name: Publish ninja-build as a static binary

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # We aren't use cross-compilation. Instead we have multiple platforms
      # with QEMU emulation providing a native environment. An alternative
      # is to use CMake to build Ninja with a cross-compiler.
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        id: image
        with:
          #platforms: linux/amd64,linux/arm64,linux/386
          file: ci/ninja-build-static/Dockerfile
          outputs: out

      - name: Test outside container
        run: out/usr/local/src/ninja-build/ninja --version

      - name: Test inside container
        run: docker run --rm ${{ steps.image.outputs.imageid }} ./ninja --version
